// AUTO-GENERATED FILE. DO NOT EDIT MANUALLY.
// Generated by: packages/frontend/apps/electron/scripts/generate-types.ts
/* eslint-disable @typescript-eslint/no-explicit-any */

import type { Observable } from 'rxjs';

type ToSubscribe<T extends Observable<unknown>> = T extends Observable<infer P> ? (callback: (payload: P) => void) => () => void : never;

export interface ElectronEvents {
  appState: {
    onState: ToSubscribe<import('@afk/electron/entries/main/state/state.service').StateService['state$']>;
  };
  ui: {
    onMaximized: ToSubscribe<import('@afk/electron/entries/main/windows/main-window.service').MainWindowManager['maximized$']>;
    onFullScreen: ToSubscribe<import('@afk/electron/entries/main/windows/main-window.service').MainWindowManager['fullScreen$']>;
  };
}
