replicaCount: 1
image:
  repository: ghcr.io/toeverything/affine
  pullPolicy: IfNotPresent
  tag: ''

imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
# map to NODE_ENV environment variable
env: 'production'
app:
  # OPEN_AGENT_SERVER_SUB_PATH
  path: ''
  # OPEN_AGENT_SERVER_HOST
  host: '0.0.0.0'
  https: true
  copilot:
    enabled: false
    secretName: copilot
    openai:
      key: ''
serviceAccount:
  create: true
  annotations: {}

podAnnotations: {}

podSecurityContext:
  fsGroup: 2000

resources:
  requests:
    cpu: '1'
    memory: 4Gi

probe:
  initialDelaySeconds: 20
  timeoutSeconds: 5

nodeSelector: {}
tolerations: []
affinity: {}
